# -*- coding: utf-8 -*-
$:.unshift("/Library/RubyMotion/lib")
require 'motion/project'
require 'motion-testflight'
require 'bundler'
Bundler.setup
Bundler.require

Motion::Project::App.setup do |app|
  # Use `rake config' to see complete project settings.
  app.name = 'MotionDiner'

  provisioning_profile = "/Users/davekapp/Library/MobileDevice/Provisioning Profiles/MotionDiner_AdHocc.mobileprovision"
  if File.exists?(provisioning_profile)
    app.codesign_certificate = "iPhone Distribution: David Kapp"
    app.identifier = "com.motiondinerapp.motiondiner"
    app.provisioning_profile = provisioning_profile

    app.entitlements["aps-environment"] = "production"
    app.entitlements["application-identifier"] = "C88DRRM863.com.motiondinerapp.motiondiner"
    app.entitlements["get-task-allow"] = false
    app.entitlements["keychain-access-groups"] = [
      app.seed_id + '.' + app.identifier
    ]
  end

  app.files_dependencies "app/welcome_view_controller.rb" => "app/diner_view_controller.rb",
                         "app/welcome_view_controller.rb" => "app/truck_view_controller.rb",
                         "app/truck_view_controller.rb"   => "app/truck.rb"

  app.icons = ["Icon.png", "Icon@2x.png", "Icon-72.png", "Icon-72@2x.png", "Icon-Small-50.png", "Icon-Small-50@2x.png", "Icon-Small.png", "Icon-Small@2x.png"]
  
  app.testflight.sdk = 'vendor/TestFlight'
  app.testflight.api_token = '0d11c8a2d44b12955c72ef06cf8b9a24_NTk0MTIzMjAxMi0wOC0yMyAxMzowNjowNS42NDQ5OTU'
  app.testflight.team_token = '05027d9118f0430bb7006b10a1ea6ad1_MTI0NTUyMjAxMi0wOC0yMyAxMzozNjoxNy41OTQ4NjU'

  # Urban Airship configuration
  # Urban Airship framework setup
  app.libs += ['/usr/lib/libz.dylib', '/usr/lib/libsqlite3.dylib']
  app.vendor_project('vendor/UrbanAirship', :static, :products => ['libUAirship-1.3.2.a'], :headers_dir => 'Common')
  app.frameworks += [
    'Security',
    'CFNetwork',
    'MobileCoreServices',
    'SystemConfiguration',
    'CoreTelephony',
    'StoreKit',
    'CoreLocation',
    'MessageUI',
    'AudioToolbox',
    'MapKit'
  ]
end
